-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN JULY J
ON H.FLAVOR = J.FLAVOR
GROUP BY J.FLAVOR
ORDER BY SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;


# SELECT F.FLAVOR
# FROM FIRST_HALF F
# JOIN JULY J
# ON F.FLAVOR = J.FLAVOR
# GROUP BY F.FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
# LIMIT 3;