-- 코드를 입력하세요
SELECT CASE WHEN PRICE < 10000 
        THEN 0
        ELSE TRUNCATE(PRICE,-4)
        END AS PRICE_GROUPS,COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUPS
ORDER BY PRICE_GROUPS 